name: '${modname}'
version: '${modversion}'
main: 'me.m1dnightninja.${modid}.spigot.${modclass}'
author: 'M1dnight_Ninja'
depend:
- MidnightCore
commands:
  skin:
    description: Main SkinSetter command
    usage: /skin <set/reset/save/reload/setnpc/setdefault/cleardefault> <player> [id]